"""Update schema for AI health requirements

Revision ID: 0c3ce2da2201
Revises: 8b33671473e8
Create Date: 2026-07-16 11:24:13.377453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c3ce2da2201'
down_revision: Union[str, Sequence[str], None] = '8b33671473e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis_results', sa.Column('record_id', sa.Integer(), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('is_pneumonia', sa.Boolean(), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('heatmap_url', sa.String(length=255), nullable=True))
    op.add_column('ai_analysis_results', sa.Column('ai_model', sa.String(length=50), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('ai_analysis_results_ibfk_1'), 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analysis_results', 'medical_records', ['record_id'], ['id'])
    op.drop_column('ai_analysis_results', 'xray_image_id')
    op.drop_column('ai_analysis_results', 'confidence_score')
    op.drop_column('ai_analysis_results', 'prediction')
    op.add_column('medical_records', sa.Column('chart_number', sa.String(length=50), nullable=False))
    op.add_column('medical_records', sa.Column('symptoms', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'medical_records', ['chart_number'])
    op.drop_column('medical_records', 'treatment_plan')
    op.drop_column('medical_records', 'diagnosis')
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_index(op.f('phone_number'), table_name='patients')
    op.create_unique_constraint(None, 'patients', ['phone'])
    op.drop_constraint(op.f('patients_ibfk_1'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'birth_date')
    op.drop_column('patients', 'phone_number')
    op.add_column('xray_images', sa.Column('record_id', sa.Integer(), nullable=False))
    op.add_column('xray_images', sa.Column('uploader_id', sa.Integer(), nullable=False))
    op.add_column('xray_images', sa.Column('shooting_datetime', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('xray_images_ibfk_1'), 'xray_images', type_='foreignkey')
    op.create_foreign_key(None, 'xray_images', 'medical_records', ['record_id'], ['id'])
    op.create_foreign_key(None, 'xray_images', 'users', ['uploader_id'], ['id'])
    op.drop_column('xray_images', 'medical_record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xray_images', sa.Column('medical_record_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'xray_images', type_='foreignkey')
    op.drop_constraint(None, 'xray_images', type_='foreignkey')
    op.create_foreign_key(op.f('xray_images_ibfk_1'), 'xray_images', 'medical_records', ['medical_record_id'], ['id'])
    op.drop_column('xray_images', 'shooting_datetime')
    op.drop_column('xray_images', 'uploader_id')
    op.drop_column('xray_images', 'record_id')
    op.add_column('patients', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('patients', sa.Column('birth_date', mysql.DATETIME(), nullable=False))
    op.add_column('patients', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('patients', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('patients_ibfk_1'), 'patients', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('phone_number'), 'patients', ['phone_number'], unique=True)
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'age')
    op.add_column('medical_records', sa.Column('diagnosis', mysql.TEXT(), nullable=True))
    op.add_column('medical_records', sa.Column('treatment_plan', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.drop_column('medical_records', 'symptoms')
    op.drop_column('medical_records', 'chart_number')
    op.add_column('ai_analysis_results', sa.Column('prediction', mysql.ENUM('NORMAL', 'PNEUMONIA'), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('confidence_score', mysql.FLOAT(), nullable=False))
    op.add_column('ai_analysis_results', sa.Column('xray_image_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analysis_results_ibfk_1'), 'ai_analysis_results', 'xray_images', ['xray_image_id'], ['id'])
    op.drop_column('ai_analysis_results', 'updated_at')
    op.drop_column('ai_analysis_results', 'ai_model')
    op.drop_column('ai_analysis_results', 'heatmap_url')
    op.drop_column('ai_analysis_results', 'confidence')
    op.drop_column('ai_analysis_results', 'is_pneumonia')
    op.drop_column('ai_analysis_results', 'record_id')
    # ### end Alembic commands ###
