"""Align User and XRayImage relations

Revision ID: 21ec01e404fc
Revises: 0c3ce2da2201
Create Date: 2026-07-16 11:50:43.455169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21ec01e404fc'
down_revision: Union[str, Sequence[str], None] = '0c3ce2da2201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'symptoms',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index(op.f('chart_number'), table_name='medical_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('chart_number'), 'medical_records', ['chart_number'], unique=True)
    op.alter_column('medical_records', 'symptoms',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
